# This is a basic workflow to help you get started with Actions

name: SonarQube GitHub Action

# Controls when the workflow will run
on: push
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
      #AST sonar Token
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarqube-scan-action@master
      with:
       projectBaseDir: sonarqube-github-action
       args: >
          -Dsonar.projectKey=ast.yogest
          -Dsonar.projectName=AST-YOGESH
          -Dsonar.verbose=true
          -Dsonar.sources=.

